/**
 * DEMO DATA — alumni mentors. Owned by the Careers Service (private to it).
 * EdOS only ever sees a mentor's public profile, inside a
 * `mentorship.offer.made` event. All people are fictional.
 */

const at = (n) => new Date(Date.now() + n * 86400000).toISOString();

export function demoAlumni() {
  return [
    {
      id: 'alm-demo-1',
      token: 'demo-a1',
      status: 'approved',
      firstName: 'Naledi',
      lastName: 'Khumalo',
      email: 'naledi.khumalo@example.com',
      gradYear: 2014,
      qualification: 'BCom (Hons) Finance',
      faculty: 'Commerce',
      role: 'Associate Director, Corporate Finance',
      organisation: 'Mercantile Capital',
      industry: 'Finance & Banking',
      location: 'Cape Town',
      expertise: ['Graduate programmes', 'CV & LinkedIn', 'Mock interviews', 'Leadership'],
      languages: ['English', 'isiZulu'],
      bio: 'Started as a graduate analyst and now lead a deal team. I remember how opaque the finance graduate market felt — happy to demystify it.',
      linkedin: 'https://www.linkedin.com/in/example-naledi',
      supportIndustries: ['Finance & Banking', 'Consulting'],
      supportFaculties: ['Commerce', 'Science'],
      skillsToMentor: ['CV & LinkedIn', 'Mock interviews', 'Graduate programmes', 'Networking', 'Applications strategy'],
      supportStages: ['Penultimate year', 'Final year', 'Honours'],
      mentoringType: '1:1 mentoring',
      meetingFormat: 'Either',
      frequency: 'Fortnightly',
      period: '12 months',
      maxMentees: 3,
      consents: { conduct: true, safeguarding: true, popia: true },
      referees: [
        { name: 'T. Adams', email: 'referee1@example.com' },
        { name: 'P. Moyo', email: 'referee2@example.com' },
      ],
      appliedAt: at(-40),
      approvedAt: at(-36),
    },
    {
      id: 'alm-demo-2',
      token: 'demo-a2',
      status: 'approved',
      firstName: 'Pieter',
      lastName: 'van der Merwe',
      email: 'pieter.vdm@example.com',
      gradYear: 2011,
      qualification: 'BSc (Eng) Civil',
      faculty: 'Engineering & the Built Environment',
      role: 'Principal Engineer',
      organisation: 'Atlantic Infrastructure',
      industry: 'Engineering',
      location: 'Stellenbosch',
      expertise: ['Career mapping', 'Workplace readiness', 'Postgraduate study'],
      languages: ['English', 'Afrikaans'],
      bio: 'Civil engineer working on water and transport projects across the Western Cape. Former Ikey Tiger (2008–2011) — I know the juggle of sport and a heavy degree.',
      linkedin: '',
      supportIndustries: ['Engineering', 'Mining & Energy', 'Public Sector'],
      supportFaculties: ['Engineering & the Built Environment'],
      skillsToMentor: ['Career mapping', 'Workplace readiness', 'Time management', 'Postgraduate study'],
      supportStages: ['Final year', 'Honours', 'Masters (career change)'],
      mentoringType: 'Either',
      meetingFormat: 'In person',
      frequency: 'Monthly',
      period: '12 months',
      maxMentees: 2,
      sportingCode: 'Rugby — Ikey Tigers',
      consents: { conduct: true, safeguarding: true, popia: true },
      appliedAt: at(-30),
      approvedAt: at(-27),
    },
    {
      id: 'alm-demo-3',
      token: 'demo-a3',
      status: 'approved',
      firstName: 'Ayesha',
      lastName: 'Patel',
      email: 'ayesha.patel@example.com',
      gradYear: 2016,
      qualification: 'LLB',
      faculty: 'Law',
      role: 'Senior Associate',
      organisation: 'Hollard & Ndlovu Attorneys',
      industry: 'Law',
      location: 'Johannesburg (online)',
      expertise: ['Applications strategy', 'Public speaking', 'Networking'],
      languages: ['English', 'Afrikaans'],
      bio: 'Commercial litigator. I help law students navigate articles applications, vac work and the reality of first-year associate life.',
      linkedin: 'https://www.linkedin.com/in/example-ayesha',
      supportIndustries: ['Law', 'Public Sector', 'Non-profit'],
      supportFaculties: ['Law', 'Humanities'],
      skillsToMentor: ['Applications strategy', 'Mock interviews', 'Public speaking', 'Networking'],
      supportStages: ['Penultimate year', 'Final year'],
      mentoringType: '1:1 mentoring',
      meetingFormat: 'Online',
      frequency: 'Fortnightly',
      period: '6 months',
      maxMentees: 2,
      consents: { conduct: true, safeguarding: true, popia: true },
      appliedAt: at(-25),
      approvedAt: at(-21),
    },
    {
      id: 'alm-demo-4',
      token: 'demo-a4',
      status: 'approved',
      firstName: 'Sizwe',
      lastName: 'Mahlangu',
      email: 'sizwe.m@example.com',
      gradYear: 2018,
      qualification: 'BSc Computer Science',
      faculty: 'Science',
      role: 'Engineering Manager',
      organisation: 'Kasi Cloud',
      industry: 'Technology',
      location: 'Cape Town',
      expertise: ['Starting a business', 'Mock interviews', 'Career mapping'],
      languages: ['English', 'isiXhosa', 'isiZulu'],
      bio: 'Software engineer turned manager at a Cape Town start-up. Ask me about technical interviews, portfolios and whether to join a start-up or a corporate.',
      linkedin: '',
      supportIndustries: ['Technology', 'Entrepreneurship'],
      supportFaculties: ['Science', 'Engineering & the Built Environment', 'Commerce'],
      skillsToMentor: ['Mock interviews', 'Career mapping', 'Starting a business', 'CV & LinkedIn'],
      supportStages: ['Penultimate year', 'Final year', 'Honours', 'Masters (career change)'],
      mentoringType: 'Group mentoring',
      meetingFormat: 'Online',
      frequency: 'Fortnightly',
      period: '6 months',
      maxMentees: 4,
      consents: { conduct: true, safeguarding: true, popia: true },
      appliedAt: at(-20),
      approvedAt: at(-18),
    },
    {
      id: 'alm-demo-5',
      token: 'demo-a5',
      status: 'pending',
      firstName: 'Thandeka',
      lastName: 'Dlamini',
      email: 'thandeka.d@example.com',
      gradYear: 2015,
      qualification: 'MBChB',
      faculty: 'Health Sciences',
      role: 'Emergency Physician',
      organisation: 'Groote Schuur Hospital',
      industry: 'Healthcare',
      location: 'Cape Town',
      expertise: ['Time management', 'Postgraduate study', 'Leadership'],
      languages: ['English', 'isiXhosa'],
      bio: 'Emergency medicine doctor. Keen to support health-sciences students thinking about specialisation, rural service and burnout-proof study habits.',
      linkedin: '',
      supportIndustries: ['Healthcare', 'Research & Academia'],
      supportFaculties: ['Health Sciences'],
      skillsToMentor: ['Time management', 'Postgraduate study', 'Study skills'],
      supportStages: ['Final year', 'Honours'],
      mentoringType: '1:1 mentoring',
      meetingFormat: 'Either',
      frequency: 'Monthly',
      period: '12 months',
      maxMentees: 2,
      consents: { conduct: true, safeguarding: true, popia: true },
      referees: [
        { name: 'Dr K. Naidoo', email: 'referee3@example.com' },
        { name: 'Prof L. Smit', email: 'referee4@example.com' },
      ],
      appliedAt: at(-2),
    },
    {
      id: 'alm-demo-6',
      token: 'demo-a6',
      status: 'pending',
      firstName: 'Lerato',
      lastName: 'Mokoena',
      email: 'lerato.mokoena@example.com',
      gradYear: 2017,
      qualification: 'BA Media & Writing',
      faculty: 'Humanities',
      role: 'Head of Brand',
      organisation: 'Ubuntu Media Group',
      industry: 'Media & Marketing',
      location: 'Durban (online)',
      expertise: ['Networking', 'Public speaking', 'CV & LinkedIn'],
      languages: ['English', 'Sesotho', 'isiZulu'],
      bio: 'Brand strategist. I love helping humanities students tell the story of their degree to employers who think they only want commerce grads.',
      linkedin: '',
      supportIndustries: ['Media & Marketing', 'Non-profit', 'Entrepreneurship'],
      supportFaculties: ['Humanities'],
      skillsToMentor: ['CV & LinkedIn', 'Networking', 'Public speaking', 'Career mapping'],
      supportStages: ['Penultimate year', 'Final year', 'Honours'],
      mentoringType: 'Either',
      meetingFormat: 'Online',
      frequency: 'Monthly',
      period: '6 months',
      maxMentees: 3,
      consents: { conduct: true, safeguarding: true, popia: true },
      appliedAt: at(-1),
    },
  ];
}

/** The profile a student may see — never contact details or referees. */
export function publicMentor(m) {
  const {
    id, firstName, lastName, gradYear, qualification, faculty, role, organisation, industry,
    location, expertise, languages, bio, linkedin, photo, mentoringType, meetingFormat,
    frequency, period, sportingCode,
  } = m;
  return {
    id, firstName, lastName, gradYear, qualification, faculty, role, organisation, industry,
    location, expertise, languages, bio, linkedin, photo, mentoringType, meetingFormat,
    frequency, period, sportingCode,
  };
}
